---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
  git:
    repoUpstreamURL: https://github.com/validatedpatterns/multicloud-gitops
    revision: rhdp-deploy
